### ISSUE TITLE
Interfacing WIFI with BeagleBone Black

### ISSUE THREAD

**Issue by BibinBabu94** [jassjagga/Capstone-Project-summer_2020#10]

**Comment by mikeshams** [comment]
1. what issues did you or others might face with connecting the wifi module to the BBB in terms of hardware and software?
2. how did you resolve them?
3. how to use the cell phone's data instead of wifi for internet connectivity purposes?

**Comment by jassjagga** [comment]
Answer 1: - Connecting the wifi module/adapter with the beaglebone black is quite easy we didn't find any problems for that but there was one change we can do to receive good wifi signal if we are using an adapter.

Answer 2: - Those changes are by adding extension cable to increase the difference between the HDMI port and Wifi adapter or for better connectivity  Disable the HDMI port by editing boot file. Because HDMI port is a right blown USB port which interfaces with wifi signal and we get reduced wifi signal.

Answer 3: - By turning on the mobile hotspot option we can use the mobile phone as a wifi modem. Which we will connect with our beaglebone as a secondary or backup wifi option in case our main one is down.
connecting it easy 
> Sudo connmanctl
>enable wifi
> services
> connect <wifi name>
> quite

WIfi is connected
