### ISSUE TITLE
Interfacing GSM with BeagleBone Black 

### ISSUE THREAD

**Issue by BibinBabu94** [jassjagga/Capstone-Project-summer_2020#11]

**Comment by mikeshams** [comment]
1. what issues did you or others might face with connecting the GSM Module to the BBB in terms of hardware and software?
2. how did you resolve them?

**Comment by jassjagga** [comment]
Answer 1: - GSM modules are a little difficult to interface with beaglebone because most of the thinkings are 2G or older GSM modules. And another thing if you want to do the programing in one fixed language then sometime you might have to write the library files of your self. Because these GSM modules mostly based on Arduino or rashpreey pie. only a few new models of gsm are coming for beaglebone like h-nanoGSM.

Answer 2: - First thing we did integration of two programming languages to interface SIM900. which save our time of writing the whole library and also our code became faster using python to send message on SIM900. Datasheet of SIM900 helps alot to understands the AT commands of SIM900.
