### ISSUE TITLE
Interfacing ThingSpeak cloud with BeagleBone Black 

### ISSUE THREAD

**Issue by mikeshams** [jassjagga/Capstone-Project-summer_2020#12]

**Comment by mikeshams** [comment]
what issues did you or others might face with connecting the ThingSpeak to the BBB?
how did you resolve them?

**Comment by BibinBabu94** [comment]
The main issue I faced was with using a string stream header file which is used for output string stream and input string stream which is used in order to give both numerical or string data to the cloud, so we had to use C++ code as the header file is not available in c code.
Another main issue was with dealy our Blood Pressure Sensor because for blood pressure we do not need data continuously so we had to put a delay for that and as well for thingspeak with has a delay of 15 seconds so we used chrono header along with threads.
