### ISSUE TITLE
Interfacing BeagleBone Black with Temperature sensor

### ISSUE THREAD

**Issue by BibinBabu94** [jassjagga/Capstone-Project-summer_2020#6]

**Comment by mikeshams** [comment]
1. What is a dtb file?
2. What issues did you or other might face regarding connecting the temperature sensor to an BBB?

**Comment by Mohsidhu** [comment]
ANS: - DT stands for device tree. device tree is a hardware description script. when we add new hardware to beagle-bone it does,t know what hardware it is and what its output. so in device tree we explain all the seensor properties and then we save that file as a DTS or .dts which means device tree source. then we compiler that code and the compiler output is .dtbo file which means device tree binary output. So know when we mention this bianry file in boot file. kernal will know which hardware it is.

**Comment by Mohsidhu** [comment]
Answer 2 : - Yes a lot because we have to explain all the properties of senor to beagle-bone and the put those changes in boot file which cause so many problems if we even miss one "," or any little mistake will corrupt the boot file which is uEnv.txt . If its corrupted we have to do flashing again. which we did like 4-5 times.
then we also got some error with eMMC old kernal blocking the u-boot_overlay file which cause no detection of the sensor. To solve that we ask question to Robert C. Neslon who mention the beaglebone kernals. 
finally we get the correct result.
