### ISSUE TITLE
Interfacing Blood Pressure Sensor with BeagleBone Black

### ISSUE THREAD

**Issue by mikeshams** [jassjagga/Capstone-Project-summer_2020#8]

**Comment by mikeshams** [comment]
1. What issues did you or others might face when connection of a Heart rate Sensor to the BBB in terms of hardware and software?
2. How did you solve them?

**Comment by jassjagga** [comment]
Ans1:- First and most important issue we faced to find out the Blood Pressure sensor which will send the data to the beaglebone. The second problem was the blood pressure we used is the finale product of one MQ company. which we modified to get data: - but the problem was to understand the data. Because It sends the data in packages and ASCCI char. which will first need to convert in Decimal numbers and we have to Verifiyies which byte in a package of 10 bytes contain the data for our required output.
Ans2:- The first problem was solved by choosing a sensor that will send the data to the LED screen. Which we thought will be used to connect the beaglebone using an LED connecting port but finally, we Find the serial pin which sends the data UART 8N1. which we understand because of the logic analyzer. Logic analyzer shows the data in channel of pulse view software. which gave us an understanding of 10 bytes of the package and which are our need bytes. So a logic analyzer is the best option to understand the unknow output of device. In this way, we solve the above mention problems.
